# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreation', models.DateTimeField(auto_created=True)),
                ('socialMedia', models.CharField(max_length=100)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('userName', models.CharField(max_length=50)),
                ('latitud', models.IntegerField()),
                ('longitud', models.IntegerField()),
                ('description', models.TextField()),
                ('type', models.TextField()),
            ],
        ),
    ]
