# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geographique_location', '0007_auto_20170220_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='user_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geolocation',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
