# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographique_location', '0008_auto_20170226_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocation',
            name='user_link',
            field=models.URLField(max_length=150),
        ),
    ]
