# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geographique_location', '0009_auto_20170226_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geolocation',
            name='user_link',
        ),
    ]
